# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/vcsreminder_gui/settingsUI.ui',
# licensing of 'src/vcsreminder_gui/settingsUI.ui' applies.
#
# Created: Sat Nov 17 00:06:32 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.profileDropdown = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.profileDropdown.setEnabled(True)
        self.profileDropdown.setObjectName("profileDropdown")
        self.horizontalLayout_2.addWidget(self.profileDropdown)
        self.addProfileBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addProfileBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/vcsreminder_icons/pngs/plus-solid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addProfileBtn.setIcon(icon)
        self.addProfileBtn.setObjectName("addProfileBtn")
        self.horizontalLayout_2.addWidget(self.addProfileBtn)
        self.deleteProfileBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteProfileBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/vcsreminder_icons/pngs/trash-alt-solid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteProfileBtn.setIcon(icon1)
        self.deleteProfileBtn.setObjectName("deleteProfileBtn")
        self.horizontalLayout_2.addWidget(self.deleteProfileBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(9, 49, 381, 201))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 28, 361, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton.setChecked(False)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setAutoExclusive(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setAutoRepeat(False)
        self.radioButton_2.setAutoExclusive(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setAutoRepeat(False)
        self.radioButton_3.setAutoExclusive(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.verticalLayout.addWidget(self.radioButton_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.reminderTime = QtWidgets.QTimeEdit(self.verticalLayoutWidget_4)
        self.reminderTime.setObjectName("reminderTime")
        self.verticalLayout_3.addWidget(self.reminderTime)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.repTime = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.repTime.setObjectName("repTime")
        self.verticalLayout_3.addWidget(self.repTime)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pathInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.pathInput.setObjectName("pathInput")
        self.horizontalLayout.addWidget(self.pathInput)
        self.browseButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(310, 260, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")
        self.applyBtn = QtWidgets.QPushButton(Dialog)
        self.applyBtn.setGeometry(QtCore.QRect(230, 260, 75, 23))
        self.applyBtn.setObjectName("applyBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Profil: ", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Settings", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Choose VCS:", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("Dialog", "Git", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("Dialog", "SVN", None, -1))
        self.radioButton_3.setText(QtWidgets.QApplication.translate("Dialog", "Perforce", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Choose Reminder Time", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Repetition Time in min", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Path to Repo:", None, -1))
        self.pathInput.setText(QtWidgets.QApplication.translate("Dialog", "C:/", None, -1))
        self.browseButton.setText(QtWidgets.QApplication.translate("Dialog", "Browse", None, -1))
        self.cancelBtn.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))
        self.applyBtn.setText(QtWidgets.QApplication.translate("Dialog", "Apply", None, -1))

